---
apiVersion: v1
kind: ConfigMap
metadata:
    name: inline-config-test-srl1-startup-config
    namespace: inline-test
data:
  REPLACED: |-
    set / interface ethernet-1/1 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv4 address 10.0.0.1/24
    set / network-instance default interface ethernet-1/1.0

