---
apiVersion: v1
kind: ConfigMap
metadata:
    name: inline-config-test-sros1-startup-config
    namespace: inline-test
data:
  REPLACED: |-
    /configure system name "sros1"
    /configure card 1 card-type iom-1
    /configure card 1 mda 1 mda-type me6-100gb-qsfp28
    /configure port 1/1/c1/1 admin-state enable

